name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macBuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make clean
        make
        
  linuxBuild:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make clean
        make
