name: C/C++ CI

on:
  push:
    branches: [ "rewrite" ]
  pull_request:
    branches: [ "rewrite" ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
